version: 0.2

env:
  variables:
    IMAGE_NAME: chat-with-docs
    IMAGE_TAG: latest
    EC2_HOST: ec2-user@13.126.45.138
    EC2_KEY_NAME: /docker/ec2-key-pem  # SSM Parameter name of your .pem content

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Docker and dependencies...
      - apt-get update
      - apt-get install -y docker.io docker-compose-plugin python3-pip unzip

      - echo Verifying Docker Compose version...
      - docker compose version

      - echo Installing AWS CLI...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install

      - echo Installing jq...
      - apt-get install -y jq

  pre_build:
    commands:
      - echo Logging in to DockerHub using credentials from SSM...
      - DOCKER_USERNAME=$(aws ssm get-parameter --name "/dockerhub/username" --region ap-south-1 --with-decryption --query "Parameter.Value" --output text)
      - DOCKER_PASSWORD=$(aws ssm get-parameter --name "/dockerhub/password" --region ap-south-1 --with-decryption --query "Parameter.Value" --output text)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - echo Fetching EC2 SSH Private Key from SSM...
      - EC2_SSH_PRIVATE_KEY=$(aws ssm get-parameter --name "$EC2_KEY_NAME" --with-decryption --region ap-south-1 --query "Parameter.Value" --output text)

  build:
    commands:
      - echo Building Docker images using Docker Compose...
      - docker compose build

  post_build:
    commands:
      - echo Deploying to EC2 instance...
      - mkdir -p ~/.ssh
      - echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/ec2-key.pem
      - chmod 400 ~/.ssh/ec2-key.pem
      - scp -i ~/.ssh/ec2-key.pem docker-compose.yml $EC2_HOST:/home/ec2-user/
      - ssh -i ~/.ssh/ec2-key.pem $EC2_HOST 'docker compose down || true && docker compose up -d'
      - echo ✅ Deployment complete

artifacts:
  files:
    - docker-compose.yml
