version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Logging in to DockerHub using credentials from Parameter Store...
      - echo "{{resolve:ssm-secure:/dockerhub/password}}" | docker login -u "{{resolve:ssm-secure:/dockerhub/username}}" --password-stdin

  pre_build:
    commands:
      - echo Pre-build phase started
      - docker --version
      - |
        if ! command -v docker-compose &> /dev/null
        then
          echo Installing docker-compose...
          pip install docker-compose
        else
          echo docker-compose already installed
        fi

  build:
    commands:
      - echo Building Docker image with docker-compose...
      - docker-compose build

  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
